name: Build SwiftUI SPM Project

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Swift
      - name: Setup Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '5.8'

      # 3️⃣ Resolve packages
      - name: Resolve Swift Packages
        run: swift package resolve

      # 4️⃣ Build project
      - name: Build Project
        run: swift build

      # 5️⃣ Run main.swift
      - name: Run SwiftUI Entry
        run: swift run
